package com.wangxy.exoskeleton.entity;

import java.math.BigDecimal;

public class DictItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.DICT_ITEM_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private String dictItemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.DICT_ENTRY_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private String dictEntryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.DICT_ITEM_NAME
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private String dictItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.DICT_ITEM_ORDER
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private BigDecimal dictItemOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.LIFECYCLE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private String lifecycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.PLATFORM
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_DICT_ITEM.REL_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    private String relCode;
    
    private String lang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.DICT_ITEM_CODE
     *
     * @return the value of TSYS_DICT_ITEM.DICT_ITEM_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public String getDictItemCode() {
        return dictItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.DICT_ITEM_CODE
     *
     * @param dictItemCode the value for TSYS_DICT_ITEM.DICT_ITEM_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setDictItemCode(String dictItemCode) {
        this.dictItemCode = dictItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.DICT_ENTRY_CODE
     *
     * @return the value of TSYS_DICT_ITEM.DICT_ENTRY_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public String getDictEntryCode() {
        return dictEntryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.DICT_ENTRY_CODE
     *
     * @param dictEntryCode the value for TSYS_DICT_ITEM.DICT_ENTRY_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setDictEntryCode(String dictEntryCode) {
        this.dictEntryCode = dictEntryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.DICT_ITEM_NAME
     *
     * @return the value of TSYS_DICT_ITEM.DICT_ITEM_NAME
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public String getDictItemName() {
        return dictItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.DICT_ITEM_NAME
     *
     * @param dictItemName the value for TSYS_DICT_ITEM.DICT_ITEM_NAME
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setDictItemName(String dictItemName) {
        this.dictItemName = dictItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.DICT_ITEM_ORDER
     *
     * @return the value of TSYS_DICT_ITEM.DICT_ITEM_ORDER
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public BigDecimal getDictItemOrder() {
        return dictItemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.DICT_ITEM_ORDER
     *
     * @param dictItemOrder the value for TSYS_DICT_ITEM.DICT_ITEM_ORDER
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setDictItemOrder(BigDecimal dictItemOrder) {
        this.dictItemOrder = dictItemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.LIFECYCLE
     *
     * @return the value of TSYS_DICT_ITEM.LIFECYCLE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public String getLifecycle() {
        return lifecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.LIFECYCLE
     *
     * @param lifecycle the value for TSYS_DICT_ITEM.LIFECYCLE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setLifecycle(String lifecycle) {
        this.lifecycle = lifecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.PLATFORM
     *
     * @return the value of TSYS_DICT_ITEM.PLATFORM
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.PLATFORM
     *
     * @param platform the value for TSYS_DICT_ITEM.PLATFORM
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_DICT_ITEM.REL_CODE
     *
     * @return the value of TSYS_DICT_ITEM.REL_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public String getRelCode() {
        return relCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_DICT_ITEM.REL_CODE
     *
     * @param relCode the value for TSYS_DICT_ITEM.REL_CODE
     *
     * @mbggenerated Wed May 20 10:54:40 CST 2020
     */
    public void setRelCode(String relCode) {
        this.relCode = relCode;
    }

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}
    
    
}