package com.wangxy.exoskeleton.entity;

public class Pagelable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_PAGELABLE.PAGE_ID
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    private String pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_PAGELABLE.LABLE_ID
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    private String lableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_PAGELABLE.LANG
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_PAGELABLE.LABLE_INFO
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    private String lableInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_PAGELABLE.PAGE_ID
     *
     * @return the value of TSYS_PAGELABLE.PAGE_ID
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public String getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_PAGELABLE.PAGE_ID
     *
     * @param pageId the value for TSYS_PAGELABLE.PAGE_ID
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_PAGELABLE.LABLE_ID
     *
     * @return the value of TSYS_PAGELABLE.LABLE_ID
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public String getLableId() {
        return lableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_PAGELABLE.LABLE_ID
     *
     * @param lableId the value for TSYS_PAGELABLE.LABLE_ID
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public void setLableId(String lableId) {
        this.lableId = lableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_PAGELABLE.LANG
     *
     * @return the value of TSYS_PAGELABLE.LANG
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_PAGELABLE.LANG
     *
     * @param lang the value for TSYS_PAGELABLE.LANG
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_PAGELABLE.LABLE_INFO
     *
     * @return the value of TSYS_PAGELABLE.LABLE_INFO
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public String getLableInfo() {
        return lableInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_PAGELABLE.LABLE_INFO
     *
     * @param lableInfo the value for TSYS_PAGELABLE.LABLE_INFO
     *
     * @mbggenerated Mon May 18 01:19:17 CST 2020
     */
    public void setLableInfo(String lableInfo) {
        this.lableInfo = lableInfo;
    }
}