package com.wangxy.exoskeleton.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wangxy.exoskeleton.entity.DictItem;

public interface DictItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRMACCOUNTING3.TSYS_DICT_ITEM
     *
     * @mbggenerated Wed May 20 10:56:25 CST 2020
     */
    int deleteByPrimaryKey(@Param("dictItemCode") String dictItemCode, @Param("dictEntryCode") String dictEntryCode, @Param("lang") String lang);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRMACCOUNTING3.TSYS_DICT_ITEM
     *
     * @mbggenerated Wed May 20 10:56:25 CST 2020
     */
    int insert(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRMACCOUNTING3.TSYS_DICT_ITEM
     *
     * @mbggenerated Wed May 20 10:56:25 CST 2020
     */
    int insertSelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRMACCOUNTING3.TSYS_DICT_ITEM
     *
     * @mbggenerated Wed May 20 10:56:25 CST 2020
     */
    DictItem selectByPrimaryKey(@Param("dictItemCode") String dictItemCode, @Param("dictEntryCode") String dictEntryCode, @Param("lang") String lang);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRMACCOUNTING3.TSYS_DICT_ITEM
     *
     * @mbggenerated Wed May 20 10:56:25 CST 2020
     */
    int updateByPrimaryKeySelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRMACCOUNTING3.TSYS_DICT_ITEM
     *
     * @mbggenerated Wed May 20 10:56:25 CST 2020
     */
    int updateByPrimaryKey(DictItem record);
    
    List<DictItem> getDictItems(@Param("dictEntryCode") String dictEntryCode, @Param("lang") String lang);   
}